### ISSUE TITLE
compilation on ubuntu 22.04

### ISSUE THREAD

**Issue by maaathieu-x** [freeDiameter/freeDiameter#50]
Hi,

I'm trying to compile freeDiameter on a ubuntu 22.04 host, using INSTALL.Ubuntu, but it fails with this error:

```
Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_33197/fast && gmake[1]: Entering directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
/usr/bin/gmake  -f CMakeFiles/cmTC_33197.dir/build.make CMakeFiles/cmTC_33197.dir/build
gmake[2]: Entering directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_33197.dir/src.c.o
/usr/bin/cc -DHAVE_MYSQL_MY_BOOL -I/usr/include/mysql  -o CMakeFiles/cmTC_33197.dir/src.c.o -c /home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.c
/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.c: In function ‘main’:
/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.c:4:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
    4 | my_bool f;
      | ^~~~~~~
      | _Bool
gmake[2]: *** [CMakeFiles/cmTC_33197.dir/build.make:78: CMakeFiles/cmTC_33197.dir/src.c.o] Error 1
gmake[2]: Leaving directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
gmake[1]: *** [Makefile:127: cmTC_33197/fast] Error 2
gmake[1]: Leaving directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'


Source file was:

#include <mysql.h>
int main() {
my_bool f;
}
dh_auto_configure: error: cd obj-x86_64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DBUILD_TESTING:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=DebianPackage -DDEFAULT_CONF_PATH:PATH=/etc/freeDiameter -DALL_EXTENSIONS:BOOL=ON .. returned exit code 1
make: *** [debian/rules:26: override_dh_auto_configure] Error 255
```

Has anyone successfully compiled freediameter on this distro ? Am I missing something  ? 

Thanks,

Mathieu

**Comment by 0-wiz-0** [comment]
I'm not using Ubuntu. The code that fails for you comes from`extensions/app_diameap/CMakeLists.txt`:
```
# Check for my_bool, deprecated in MySQL 8.0
SET(CHECK_MYSQL_MY_BOOL "
#include <mysql.h>
int main() {
my_bool f;
}")
```
I haven't used this extension. If you don't need it, perhaps disable it.

**Comment by maaathieu-x** [comment]
then I have this error:

```
Determining if the function sctp_connectx exists failed with the following output:
Change Dir: /home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_9a6ee/fast && gmake[2]: Entering directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
/usr/bin/gmake  -f CMakeFiles/cmTC_9a6ee.dir/build.make CMakeFiles/cmTC_9a6ee.dir/build
gmake[3]: Entering directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9a6ee.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=sctp_connectx -o CMakeFiles/cmTC_9a6ee.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.22/Modules/CheckFunctionExists.c
Linking C executable cmTC_9a6ee
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9a6ee.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=sctp_connectx -rdynamic CMakeFiles/cmTC_9a6ee.dir/CheckFunctionExists.c.o -o cmTC_9a6ee 
/usr/bin/ld: CMakeFiles/cmTC_9a6ee.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x14): undefined reference to `sctp_connectx'
collect2: error: ld returned 1 exit status
gmake[3]: *** [CMakeFiles/cmTC_9a6ee.dir/build.make:99: cmTC_9a6ee] Error 1
gmake[3]: Leaving directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
gmake[2]: *** [Makefile:127: cmTC_9a6ee/fast] Error 2
gmake[2]: Leaving directory '/home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
```

not sure it's supposed to compile on Ubuntu 22.04. I'll try on ubuntu 20.04 when I have time

**Comment by sdecugis** [comment]
There is an older issue on 20.04 already... Sorry for that, I need to spend some time to have a look. It is time-consuming to keep up with Ubuntu evolution ^^'

**Comment by velichkov** [comment]
> /home/mathieu/freeDiameter/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.c:4:1: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
>     4 | my_bool f;

To resolve the above error you need to install `libmysqlclient-dev` package
```
sudo apt install libmysqlclient-dev
```

**Comment by velichkov** [comment]
> CheckFunctionExists.c:(.text+0x14): undefined reference to `sctp_connectx'

And to resolve this you need to install `libsctp-dev` pacakge

```
sudo apt install libsctp-dev
```
Also read INSTALL.Ubuntu
https://github.com/freeDiameter/freeDiameter/blob/a9f684f314a736d9ff4f36115b7c8c8615acc48e/INSTALL.Ubuntu#L19-L39

**Comment by sdecugis** [comment]
A few changes merged today should solve the problem: https://github.com/freeDiameter/freeDiameter/commit/a48460b307d94b365715fb7dadf7a6a0d4fcb6e9
